steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -lc
      - |
        echo "Commit: $COMMIT_SHA"
        pwd
        echo "== files =="
        find . -maxdepth 2 -type f | sort

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t","southamerica-east1-docker.pkg.dev/$PROJECT_ID/kickflip/kickflip:$SHORT_SHA",
        "-t","southamerica-east1-docker.pkg.dev/$PROJECT_ID/kickflip/kickflip:latest",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args: ["push","southamerica-east1-docker.pkg.dev/$PROJECT_ID/kickflip/kickflip:$SHORT_SHA"]

  - name: gcr.io/cloud-builders/docker
    args: ["push","southamerica-east1-docker.pkg.dev/$PROJECT_ID/kickflip/kickflip:latest"]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run","deploy","kickflip",
        "--image","southamerica-east1-docker.pkg.dev/$PROJECT_ID/kickflip/kickflip:latest",
        "--region","southamerica-east1",
        "--allow-unauthenticated",
        "--port","8501",
        "--memory","1Gi"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
