name: retrain-model

on:
  schedule:
    - cron: "0 9 * * 1"  # Lunes 09:00 UTC
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train
        run: python train.py
      - name: Commit model artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add models/*.joblib models/*.json || true
          git commit -m "Auto: retrain model" || echo "No changes"
          git push
